export const surpriseMePrompts = [
  'An elegant armchair shaped like a giant avocado, with a rich velvet texture and gold-trimmed edges, set in a luxurious modern living room.',
  'A surreal oil painting by Salvador Dalí depicting a cat dressed as a philosopher, deep in thought as it plays an intricate game of checkers with a mouse on a floating chessboard in a dreamlike desert landscape.',
  'A group of adorable teddy bears dressed in traditional Japanese kimonos shopping for groceries in a bustling Tokyo market, illustrated in the classic ukiyo-e art style.',
  'A humanoid robot with a sleek, futuristic design playing chess against a grandmaster in an oil painting by Henri Matisse, surrounded by vibrant, swirling colors.',
  'A panda scientist in a high-tech laboratory, wearing a lab coat and goggles, mixing glowing, bubbling chemicals that emit colorful sparks, depicted in high-quality digital art.',
  'A stunning macro 35mm photograph of two tiny mice vacationing in Hawaii, both wearing miniature floral swimsuits and carrying surfboards as they prepare to ride the waves.',
  'A hyper-realistic 3D render of a bright and colorful tropical fish swimming gracefully in an aquarium with a dark blue neon-lit background.',
  'An astronaut, in a sleek, futuristic space suit, lounging by an infinity pool in a tropical space resort with floating palm trees and a neon vaporwave aesthetic.',
  'A regal capybara sitting on a golden throne, wearing elaborate medieval royal robes with intricate embroidery, a magnificent gemstone-encrusted crown, and an air of wisdom.',
  'A magnificent stained glass window depicting a delicious, oversized hamburger and crispy golden fries, illuminated by sunlight streaming through the colorful glass.',
  'A futuristic city painted in a mix of pencil and watercolor, filled with towering skyscrapers, bright neon signs, and flying cars soaring through the sky.',
  'A breathtaking indoor lounge bathed in golden sunlight, featuring a pool with crystal-clear water and another filled with soft, pastel pink liquid, surrounded by lush greenery and modern architecture.',
  'A wise Shiba Inu dressed as a mystical fortune-teller, sitting inside a giant glowing hamburger, gazing into a crystal ball as it reveals someone’s fate.',
  'A humorous and imaginative take on "Girl with a Pearl Earring" by Johannes Vermeer, replacing the girl with an adorable sea otter wearing an elegant pearl earring.',
  'A grumpy cat sitting inside the cockpit of a spaceship, gazing out at the vastness of space, drawn in expressive oil pastel strokes.',
  'A fox painted in the dreamy, swirling brushstrokes of Van Gogh’s "Starry Night," surrounded by a magical, star-filled sky.',
  'A steaming bowl of soup that appears alive, with monster-like features, crafted entirely from soft, knitted wool, making it both eerie and adorable.',
  'A charming plush toy robot sitting against a bright yellow wall, looking up curiously with expressive LED eyes and a small antenna on its head.',
  'A nostalgic synthwave-style sunset with neon pink and purple hues reflecting on the ocean, glowing gridlines fading into the horizon, and a silhouetted palm tree swaying in the breeze.',
  'Two towering futuristic skyscrapers connected by a lush, plant-covered skybridge, set against a glowing cyberpunk cityscape in a high-detail digital painting.',
  'A hyper-realistic 3D render of a massive hot air balloon, covered in a dazzling rainbow gradient, soaring high above a serene lake reflecting its colors.',
  'A dynamic comic book cover featuring a futuristic superhero in a sleek, cybernetic suit, wearing high-tech headphones, ready for an epic mission.',
  'A mesmerizing explosion of vivid, multicolored powder suspended in mid-air against a deep black background, captured in high-speed photography.',
  'A heartwarming photo of a fluffy Samoyed dog with its tongue out, lovingly embracing a white Siamese cat as they both bask in the soft afternoon light.',
  'A whimsical photograph of a towering white-furred yeti standing in the center of a purple room, holding a steaming cup of tea and looking at the camera curiously.',
  'A playful take on Michelangelo’s "David," with the iconic marble statue wearing modern headphones and DJing in a neon-lit club.',
  'A fierce samurai in ornate, battle-worn armor, riding a majestic black horse across the barren red landscape of Mars, captured in vintage lomography style.',
  'A sleek, modern Cadillac driving along a rain-slicked Gardiner Expressway in Toronto, illuminated by a golden lens flare and the city skyline at dusk, captured in 50mm photography.',
  'A lifelike photograph of a young woman with deep blue eyes and long, flowing blonde hair, caught in a moment of serene contemplation.',
  'A lone man standing before a swirling, glowing stargate, peering into the infinite unknown of another dimension.',
  'A hilarious crossover featuring SpongeBob SquarePants lost in the eerie, found-footage world of "The Blair Witch Project."',
  'A velociraptor in a snazzy apron running a bustling hotdog stand, expertly flipping sausages on a sizzling grill, shot in a gritty lomography style.',
  'A cyberpunk-inspired night scene of Kowloon’s crowded streets, where a man in a futuristic jacket walks through neon-lit alleyways, shot with a 50mm lens.',
  'A lively BBQ grill that has come to life, with animated eyes and a toothy grin, flipping juicy burgers in the style of a Pixar animated movie.',
  'A neon-lit, futuristic cyborg nightclub packed with robotic dancers and pulsing electronic music, with an ultra-modern cyberpunk aesthetic.',
  'A reimagined 1990s Japanese anime adaptation of Star Wars, featuring bold cel-shaded action sequences, dramatic character expressions, and intense lightsaber duels.',
  'A professionally photographed gourmet burger, styled to resemble a perfectly aligned Rubik’s cube with each ingredient forming a colorful square.',
  'A synthwave-inspired hedgehog wearing cybernetic armor, standing atop a futuristic city skyline, with neon streaks and digital rain falling around it.',
  'A detailed astronaut photograph capturing a tense first encounter with an alien life form on a distant planet, with mist rolling over an otherworldly landscape.',
  'A lifelike scene of a towering dinosaur exploring the vibrant streets of Cape Town, surrounded by amazed onlookers.',
  'A digital painting of a man deeply in love with his sleek, AI-powered computer, gazing at it as romantic light glows around them.',
  'A cyberpunk-style photograph of a half-human, half-machine cyborg exploring the neon streets of Tokyo at night, captured in a gritty lomography aesthetic.',
  'A black-and-white 1920s photograph of Dracula strolling down a bustling New York City street, dressed in a vintage trench coat, blending into the crowd.',
  'A futuristic airplane soaring through a neon-saturated synthwave sky, leaving behind a trail of glowing pink and purple vapor.',
  'A solitary figure walking through the rain-soaked streets of Tokyo, bathed in reflections of bright neon signs, captured in stunning 50mm photography.',
  'A breathtaking digital painting of a space shuttle gliding over Cape Town’s cityscape, blending futuristic elements with earthly beauty.',
];
